# -*- coding: utf-8 -*-
"""Copy of FND.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1804OpS2i49ganMsJuN0x9xHDxf_0B73r

1. Imports & SetUp
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

import joblib

"""Load & Prepare Data"""

# Load the fake/real datasets

fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

fake_df['label'] = 1  # fake
true_df['label'] = 0  # real

# Combine datasets
news_df = pd.concat([fake_df, true_df], ignore_index=True)
# shuffle so model doesn't see fake then real in blocks
news_df = news_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Dataset shape:", news_df.shape)
news_df.head()

"""3. Prepare Text Columns"""

# Combine title + text fields
news_df['content'] = news_df['title'].fillna('') + ' ' + news_df['text'].fillna('')
news_df = news_df[['content', 'label']]

"""4. Light Text Cleaning"""

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

news_df['clean_text'] = news_df['content'].apply(clean_text)

"""5. Classical ML Models

5.1 Split Data
"""

X = news_df['clean_text']
y = news_df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""5.2 Vectorizers"""

tfidf = TfidfVectorizer(ngram_range=(1,2), max_features=50000, stop_words='english')
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

"""5.3 Train ML Models (LR, SVM, Naive Bayes)"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, class_weight='balanced'),
    "Linear SVM": LinearSVC(class_weight='balanced', max_iter=5000),
    "Naive Bayes": MultinomialNB()
}

results = []

for name, model in models.items():
    model.fit(X_train_tfidf, y_train)
    preds = model.predict(X_test_tfidf)
    acc = accuracy_score(y_test, preds)

    print(f"\n{name} Accuracy: {acc:.4f}")
    print(classification_report(y_test, preds))

    results.append((name, acc))

"""5.4 Plot Comparison"""

model_names, acc_values = zip(*results)
plt.bar(model_names, acc_values)
plt.ylabel("Accuracy")
plt.title("Classical ML Model Comparison")
plt.show()

"""6. Save Best Classical Model (Calibrated SVM)"""

from sklearn.calibration import CalibratedClassifierCV

base_svm = LinearSVC(class_weight='balanced')
calib_svm = CalibratedClassifierCV(base_svm, cv=3)

calib_svm.fit(X_train_tfidf, y_train)

joblib.dump(calib_svm, "svm_fake_news_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

"""7. Prediction Function (Classical Model)"""

def predict_news_svm(text):
    clean = clean_text(text)
    vec = tfidf.transform([clean])
    pred = calib_svm.predict(vec)[0]
    prob = calib_svm.predict_proba(vec)[0][pred]
    label = "REAL ✅" if pred == 0 else "FAKE ❌"
    return f"{label} (Confidence: {prob:.2f})"

""" Confusion Matrix"""

# Confusion Matrix for Classical Model

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# pick best model (you can change if needed)
best_clf = calib_svm
best_preds = best_clf.predict(X_test_tfidf)

cm = confusion_matrix(y_test, best_preds)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["REAL", "FAKE"],
            yticklabels=["REAL", "FAKE"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Classical Model (SVM)")
plt.show()

""" Normalized Confusion Matrix"""

cm_norm = confusion_matrix(y_test, best_preds, normalize='true')

plt.figure(figsize=(5,4))
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap="Greens",
            xticklabels=["REAL", "FAKE"],
            yticklabels=["REAL", "FAKE"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Normalized Confusion Matrix - Classical Model (SVM)")
plt.show()

""" Text Length Distribution"""

plt.figure(figsize=(7,4))
sns.histplot(news_df[news_df['label']==0]['clean_text'].apply(lambda x: len(x.split())),
             color='green', kde=True, label='REAL')
sns.histplot(news_df[news_df['label']==1]['clean_text'].apply(lambda x: len(x.split())),
             color='red', kde=True, label='FAKE')
plt.legend()
plt.title("Text Length Distribution (Real vs Fake)")
plt.show()

""" Word Clouds"""

# WordClouds for Real vs Fake

from wordcloud import WordCloud

real_text = " ".join(news_df[news_df['label']==0]['clean_text'].tolist())
fake_text = " ".join(news_df[news_df['label']==1]['clean_text'].tolist())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.imshow(WordCloud(width=800, height=400, background_color='white').generate(real_text))
plt.title("REAL News WordCloud")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(WordCloud(width=800, height=400, background_color='white').generate(fake_text))
plt.title("FAKE News WordCloud")
plt.axis("off")

plt.show()

# --- real world demo for the SVM model ---

svm_test_samples = [
    "India launches new satellite for climate monitoring",
    "Government announces new policy for electric vehicles",
    "World will end tomorrow, claims anonymous scientist",
    "Apple reveals official date for its next iPhone event",
    "Doctors find overnight cure for cancer",
]

for t in svm_test_samples:
    print("\nSVM →", t)
    print("Prediction:", predict_news_svm(t))

"""8. Demo: User Input + Confidence Score"""

user_text = input("Enter a news headline or article snippet: ").strip()

cleaned = clean_text(user_text)
vec = tfidf.transform([cleaned])

pred = calib_svm.predict(vec)[0]
probs = calib_svm.predict_proba(vec)[0]

label = "REAL" if pred == 0 else "FAKE"
confidence = probs[pred]

print("\nPrediction:", label)
print(f"Confidence: {confidence*100:.2f}%")

print("\nClass probabilities:")
print(f"  REAL: {probs[0]*100:.2f}%")
print(f"  FAKE: {probs[1]*100:.2f}%")

"""Level 2: DistilBERT

1. DistilBert Setup
"""

import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    get_linear_schedule_with_warmup
)

"""2. Use Raw Text (Not Cleaned)"""

df_small = news_df.sample(5000, random_state=42)  # small subset for speed

X_small = df_small['content']
y_small = df_small['label']

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_small, y_small, test_size=0.2, random_state=42, stratify=y_small
)

"""3. Tokenization"""

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")
max_len = 512

train_enc = tokenizer(list(X_train_b), truncation=True, padding=True, max_length=max_len)
test_enc = tokenizer(list(X_test_b), truncation=True, padding=True, max_length=max_len)

"""4. Dataset Class"""

class NewsDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(int(self.labels.iloc[idx]))
        return item

    def __len__(self):
        return len(self.labels)

"""5. Data Loaders"""

train_dataset = NewsDataset(train_enc, y_train_b)
test_dataset = NewsDataset(test_enc, y_test_b)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

"""6. Model, Optimizer, Scheduler"""

device = "cuda" if torch.cuda.is_available() else "cpu"

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
).to(device)

optimizer = AdamW(model.parameters(), lr=2e-5)

epochs = 2
total_steps = len(train_loader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

"""7. Training Loop"""

# DistilBERT Training (Optimized FP16)

from tqdm.auto import tqdm
import torch

# put model in training mode
model.train()

# GradScaler enables safe mixed-precision on GPU (2–3x faster)
scaler = torch.cuda.amp.GradScaler()

for epoch in range(epochs):
    total_loss = 0
    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}", leave=True)

    for batch in progress_bar:
        # move data to GPU
        batch = {k: v.to(device) for k, v in batch.items()}

        optimizer.zero_grad()

        # mixed precision forward pass for speed
        with torch.cuda.amp.autocast():
            outputs = model(**batch)
            loss = outputs.loss

        # backward pass (scaled for FP16 stability)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # update learning rate according to scheduler
        scheduler.step()

        total_loss += loss.item()
        progress_bar.set_postfix(loss=loss.item())

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1} | Average training loss: {avg_loss:.4f}")

"""8. Evaluation"""

# DistilBERT Evaluation

model.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for batch in test_loader:
        batch = {k: v.to(device) for k, v in batch.items()}

        outputs = model(**batch)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(batch["labels"].cpu().numpy())

# accuracy & report
print("DistilBERT Accuracy:", accuracy_score(all_labels, all_preds))
print(classification_report(all_labels, all_preds))

"""9. Save DistilBERT Model"""

model.save_pretrained("distilbert_fake_news")
tokenizer.save_pretrained("distilbert_fake_news")

from transformers import DistilBertForSequenceClassification, DistilBertTokenizer
import torch

# Load saved model and tokenizer
model = DistilBertForSequenceClassification.from_pretrained("./distilbert_fake_news")
tokenizer = DistilBertTokenizer.from_pretrained("./distilbert_fake_news")

# Set to evaluation mode
model.eval()

"""10. DistilBERT Prediction Function"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

def predict_news_bert(text):
    # Tokenize
    enc = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding="max_length",
        max_length=128
    )

    # Move ALL tensors to the correct device
    for k in enc:
        enc[k] = enc[k].to(device)

    # Prediction
    with torch.no_grad():
        outputs = model(**enc)
        logits = outputs.logits
        probs = torch.softmax(logits, dim=1)
        pred = torch.argmax(probs, dim=1).item()

    label = "REAL ✅" if pred == 0 else "FAKE ❌"
    conf = probs[0][pred].item()
    return f"{label} (Confidence: {conf:.2f})"

# --- real world demo for the SVM model ---

svm_test_samples = [
    "India launches new satellite for climate monitoring",
    "Government announces new policy for electric vehicles",
    "World will end tomorrow, claims anonymous scientist",
    "Apple reveals official date for its next iPhone event",
    "Doctors find overnight cure for cancer",
]

for t in svm_test_samples:
    print("\nSVM →", t)
    print("Prediction:", predict_news_svm(t))

# ---- Real-life testing for DistilBERT ----

bert_test_samples = [
    "India launches new satellite to monitor climate patterns",
    "Government approves new policy for renewable energy expansion",
    "Apple officially confirms the iPhone 16 launch event next month",
    "Scientists discover a way to reverse aging in humans",
    "World will end next week, claims anonymous scientist on social media",
]

for text in bert_test_samples:
    print("\nBERT →", text)
    print("Prediction:", predict_news_bert(text))

# User input demo for fake news detection
user_text = input("Enter a news snippet to check: \n")

# DistilBERT prediction
bert_result = predict_news_bert(user_text)

# SVM prediction
svm_result = predict_news_svm(user_text)

# Display results in a human-friendly way
print("\n=== Fake News Detection Results ===")
print(f"News: {user_text}\n")
print(f"DistilBERT Prediction: {bert_result}")
print(f"SVM Prediction: {svm_result}")

"""Overall, both classical ML and transformer models performed well, but DistilBERT proved to be the most effective approach for fake news detection."""

news_df['label'].value_counts()

news_df.sample(5)

